apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: srvthreds

resources:
- ../../base/namespace.yaml
- ../../base/configmap.yaml
- mongo.yaml
- redis.yaml
- rabbitmq.yaml
- ../../base/srvthreds-bootstrap.yaml
- ../../base/srvthreds-engine.yaml
- ../../base/srvthreds-session-agent.yaml
- ../../base/srvthreds-persistence-agent.yaml

images:
- name: srvthreds
  newTag: dev

patchesStrategicMerge:
- configmap-dev.yaml

commonLabels:
  environment: development
  version: dev