# ignore files
*.md
*.yml
infrastructure/deployment/cli.ts
infrastructure/deployment/deployment.ts

# ignore folders
config/
deploy/
node_modules/
infrastructure/local/compose
infrastructure/local/scripts
infrastructure/kubernetes
infrastructure/terraform
infrastructure/docs
scripts/
