# ignore files
*.md
*.yml
.DS_Store
.gitignore

*.log
.prettier*
*.eslint*

# ignore folders
.claude/
.idea/
.git/
.github/
config/
deploy/
infrastructure/
node_modules/
scripts/
.vscode/

# include files
!infrastructure/tools/deployment-cli/assets/