#!/bin/sh
google-chrome --user-data-dir=/home/rburson/chrome_profiles/demo1 --new-window --window-size="200,600" --window-position="600,10" "http://localhost:3000/rms" & 2>&1
google-chrome --user-data-dir=/home/rburson/chrome_profiles/demo2 --new-window --window-size="200,600" --window-position="2300,10" "http://localhost:3000/assembly" & 2>&1
