#!/bin/sh

~/Android/Sdk/emulator/emulator -avd Pixel_6a_API_34 -accel on & 2>&1
~/Android/Sdk/emulator/emulator -avd Pixel_7_API_34 -accel on & 2>&1
#~/Android/Sdk/emulator/emulator -avd Pixel_8a_API_34 -accel on & 2>&1

