services:
  # Command runner for environment setup
  srvthreds-bootstrap:
    build:
      context: ../../../
      dockerfile: srvthreds/infrastructure/dockerCompose/Dockerfile.cmdRunner
    container_name: srvthreds-bootstrap
    # entrypoint: []
    command: ["npm", "run", "bootstrap", "--", "-p", "dev"]
    environment:
      - NODE_ENV=development
    restart: "no"  # Run once and exit
    network_mode: "host"
    # networks:
    #   - storage-net

  # SrvThreds Engine Service
  srvthreds-engine:
    build:
      context: ../../../
      dockerfile: srvthreds/infrastructure/dockerCompose/Dockerfile
    container_name: srvthreds-engine
    network_mode: "host"
    command: ["node", "/app/dist-server/index.js", "-d"]
    depends_on:
      srvthreds-bootstrap:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=development
      # - MONGO_HOST=mongo-repl-1:27017,mongo-repl-2:27017,mongo-repl-3:27017
      # - REDIS_HOST=redis
    restart: unless-stopped
    # networks:
    #   - storage-net
    #   - app-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'

  # SrvThreds Session Agent
  srvthreds-session-agent:
    build:
      context: ../../../
      dockerfile: srvthreds/infrastructure/dockerCompose/Dockerfile
      # dockerfile: srvthreds/Dockerfile
    container_name: srvthreds-session-agent
    network_mode: "host"
    command: ["node", "/app/dist-server/agent/agent.js", "-c", "session_agent", "-d"]
    depends_on:
      srvthreds-bootstrap:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=development
      # - MONGO_HOST=mongo-repl-1:27017,mongo-repl-2:27017,mongo-repl-3:27017
      # - REDIS_HOST=redis
    restart: unless-stopped
    # networks:
    #   - storage-net
    #   - app-net
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

  # SrvThreds Persistence Agent
  srvthreds-persistence-agent:
    build:
      context: ../../../
      dockerfile: srvthreds/infrastructure/dockerCompose/Dockerfile
      # dockerfile: srvthreds/Dockerfile
    container_name: srvthreds-persistence-agent
    network_mode: "host"
    command: ["node", "/app/dist-server/agent/agent.js", "-c", "persistence_agent", "-d"]
    depends_on:
      srvthreds-bootstrap:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=development
      # - MONGO_HOST=mongo-repl-1:27017,mongo-repl-2:27017,mongo-repl-3:27017
      # - REDIS_HOST=redis
    restart: unless-stopped
    # networks:
    #   - storage-net
    #   - app-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
        reservations:
          memory: 256M
          cpus: '0.2'

# networks:
#   storage-net:
#     driver: bridge
#   app-net:
#     driver: bridge

# volumes:
#   mongo-data-2:
#   mongo-data-3:
  # nginx-session:
  #   # running in host mode because we're not running the node server in a container for demo purposes...
  #   network_mode: host
  #   container_name: nginx-session
  #   hostname: nginx-session
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./.docker/config/nginx-session:/etc/nginx
  #     - ./.docker/config/ssl:/etc/ssl
